[package]
name = "fulturate"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.12", features = ["macros", "auto-send", "rustls"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
pretty_env_logger = "0.5"
log = "0.4"
sysinfo = "0.33.1"
gemini-rs = "1.1.0"
